---
title: "Outdoors introduction pathway"
author: "Natalia Ciria"
editor: visual
bibliography: references.bib
execute:
  output: false
---

```{r}
#| purl: false
# This chunk is excluded from the unified script

# Convert the latest version of "set_up" qmd file to a plain R script
knitr::purl("set_up_v2.qmd", documentation = 2, output = "unified_script/set_up_v2.R")
# Specify farm_id
farm_id<-"bc6_v1"
# Source the setup script
source("unified_script/set_up_v2.R")
```

```{r}
message("\nFARM WILDLIFE PATHWAY: ")
```

## Wildlife area effect module

### Prepare data

```{r, message=FALSE}
wildlife_area_data<-get_region_code(bsg, pathway = "farm")%>%
  left_join(tidy_prefix(bsg, "outdoors"))

wildlife_area_data<-wildlife_area_data%>%
  mutate(surface="soil")%>%
  left_join(pathogen_surface)%>%
  hjoin_region(wildlife_region)%>%
  hjoin_region(wildlife_pathogen_region)%>%
  left_join(wildlife_point_density)%>%
  hjoin_region(pathogen_region)%>%
  left_join(pathogen)%>%
  #Filter those that have wildlife prevalence
  filter(pathogen%in%
           unique(wildlife_pathogen_region$pathogen[wildlife_pathogen_region$wildlife_prev_mode>0]))

message("\nwildlife_area_data (",paste(dim(wildlife_area_data), collapse=", "),") created")
```

### Prepare what-if

```{r}
if(admin_wif){
  #There are no admin what-ifs in this module, but we set up wif for compatibility
  wildlife_area_data<-set_up_wif(wildlife_area_data)
}
```

### Evaluate

```{r}
wildlife_area_exp<-c(
  wildlife_area_link = wildlife_area_link_exp,
  wildlife_area_inf=area_exp)  

wildlife<-mcmodule::eval_module(
  exp = wildlife_area_exp,
  data = wildlife_area_data) 

wildlife<-mcmodule::agg_totals(
  mcmodule=wildlife,
  mc_name=c("area_inf"),
  agg_keys = c("pathogen", "scenario_id", "farm_id"))

wildlife<-mcmodule::add_prefix(wildlife)
```

## Wildlife contact points module

### Prepare data

```{r, message=FALSE}
farm_census_data<-tidy_prefix(bsg, "farm_census")%>%
  pivot_longer(
      cols = starts_with("cattle"),
      names_to = "animal_category",
      values_to = "census",
      values_drop_na = TRUE
    )%>%
  left_join(animal)%>%
  mutate(livestock_units=census*livestock_units)

wildlife_water_data<-wildlife_area_data%>%
  pivot_longer(
    cols = ends_with("_p")&!mud_p&!sum_p,
    names_to = "waterpoint_type",
    values_to = "point_p",
    values_drop_na = TRUE
  )%>%
  mutate(
    animals_n=sum(farm_census_data$census),
    livestock_units=sum(farm_census_data$livestock_units),
    contact_point_type=sub("_p", "", waterpoint_type),
    mud_p=ifelse(contact_point_type%in%c("low", "high"),ifelse(mud,as.numeric(gsub("%", "", mud_p)),0),100)/100,
    contact_point_p=as.numeric(gsub("%", "", point_p))/100
  )

wildlife_water_data<-wildlife_water_data%>%
  left_join(wildlife_point)%>%
  left_join(animal_point)


#CHANCHULLO CUTRE PARA RESOLVER #186 de cara a las granjas de diciembre
if(farm_id%in%c("bc6_v2", "bc10_v2")){
  wildlife_feed_data<-wildlife_water_data%>%
    filter(contact_point_type=="waterhole")%>%
    mutate(contact_point_type="feed")

  wildlife_contact_data<-wildlife_water_data%>%
    bind_rows(wildlife_feed_data)
}else{
  wildlife_contact_data<-wildlife_water_data
}


message("\nwildlife_contact_data (",paste(dim(wildlife_contact_data), collapse=", "),") created")
```

### Admin what-if

```{r}
if(admin_wif){
  #Avoid mud on wateres
  wildlife_contact_data<-wif_no_mud(wildlife_contact_data, scenario="Avoid mud on wateres")
  wildlife_contact_data<-wif_high_waterer(wildlife_contact_data, scenario="Use high wateres")
}
```

### Evaluate

```{r}
wildlife_contact_exp<-c(
  wildlife_link = wildlife_contact_link_exp,
  wildlife_time = time_exp,
  wildlife_indir_contact=indir_contact_exp)

wildlife_contact<-mcmodule::eval_module(
  exp = wildlife_contact_exp,
  data = wildlife_contact_data,
  keys = "scenario_id")

wildlife_contact<-mcmodule::trial_totals(
  mcmodule = wildlife_contact,
  mc_names = c("indir_contact"),
  trials_n = "animals_n",
  level_suffix = c(set="herd"))

wildlife_contact<-mcmodule::agg_totals(
  mcmodule=wildlife_contact,
  mc_name=c("indir_contact_herd"),
  agg_keys = c("pathogen", "scenario_id", "farm_id", "contact_point_type"),
  agg_suffix = "point")

wildlife_contact<-mcmodule::agg_totals(
  mcmodule=wildlife_contact,
  mc_name=c("indir_contact_herd"),
  agg_keys = c("pathogen", "scenario_id", "farm_id"))

wildlife_contact<-mcmodule::add_prefix(wildlife_contact)
```

## Combine modules

```{r}
wildlife<-mcmodule::combine_modules(wildlife, wildlife_contact)

wildlife<-mcmodule::at_least_one(
  mcmodule = wildlife, 
  mc_names = c("wildlife_area_inf_agg","wildlife_contact_indir_contact_herd_agg"),
  name = "wildlife_inf_agg")

print_pathway_risk(wildlife, "wildlife_inf_agg")

message("\nFARM WILDLIFE PATHWAY OK!")
```
